/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/chat` | `/chat`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/scan` | `/scan`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/reset-password` | `/reset-password`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-up/ai-questions-allergy` | `/sign-up/ai-questions-allergy`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-up/ai-questions-health` | `/sign-up/ai-questions-health`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-up/basic-details` | `/sign-up/basic-details`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-up/set-password` | `/sign-up/set-password`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/dashboard` | `/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/chat` | `/chat`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/scan` | `/scan`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/reset-password` | `/reset-password`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/sign-up/ai-questions-allergy` | `/sign-up/ai-questions-allergy`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/sign-up/ai-questions-health` | `/sign-up/ai-questions-health`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/sign-up/basic-details` | `/sign-up/basic-details`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/sign-up/set-password` | `/sign-up/set-password`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/dashboard${`?${string}` | `#${string}` | ''}` | `/dashboard${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/chat${`?${string}` | `#${string}` | ''}` | `/chat${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/scan${`?${string}` | `#${string}` | ''}` | `/scan${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/reset-password${`?${string}` | `#${string}` | ''}` | `/reset-password${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/sign-up/ai-questions-allergy${`?${string}` | `#${string}` | ''}` | `/sign-up/ai-questions-allergy${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/sign-up/ai-questions-health${`?${string}` | `#${string}` | ''}` | `/sign-up/ai-questions-health${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/sign-up/basic-details${`?${string}` | `#${string}` | ''}` | `/sign-up/basic-details${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/sign-up/set-password${`?${string}` | `#${string}` | ''}` | `/sign-up/set-password${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/chat` | `/chat`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/scan` | `/scan`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/reset-password` | `/reset-password`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-up/ai-questions-allergy` | `/sign-up/ai-questions-allergy`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-up/ai-questions-health` | `/sign-up/ai-questions-health`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-up/basic-details` | `/sign-up/basic-details`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-up/set-password` | `/sign-up/set-password`; params?: Router.UnknownInputParams; };
    }
  }
}
